import {StyleSheet} from 'react-native';
import Colors from '@/assets/colors/Colors';
import {typography} from '@/styles/typography';

const {subhead02, subhead03, headline, body01, bodyLong01, caption} =
  typography;

const HomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.gray_01,
  },
  containerHeader: {
    height: 210,
    overflow: 'hidden',
  },
  containerIcons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 23,
  },
  containerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  containerCarouselTicket: {
    marginHorizontal: 6,
    shadowColor: '#171717',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  containerPagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -15,
    marginBottom: 15,
  },
  paginationDot: {
    width: 6,
    height: 6,
    borderRadius: 6,
    margin: 3.5,
  },
  activeDot: {
    backgroundColor: Colors.sub_04,
  },
  inactiveDot: {
    backgroundColor: Colors.gray_05,
  },
  containerAdImage: {
    marginTop: 39,
  },
  containerAd: {
    position: 'absolute',
    top: 15,
    left: 20,
    width: 39,
    height: 18,
    backgroundColor: '#F2F2F2',
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textAd: {
    ...caption,
    color: '#6F6F6F',
  },
  containerTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 48,
    marginBottom: 20,
  },
  textTitle: {
    ...headline,
    color: Colors.gray_12,
  },
  textWriteReview: {
    ...body01,
    color: Colors.gray_08,
  },
  containerTicket: {
    flexDirection: 'row',
  },
  ticket1: {
    width: 250,
    height: 150,
    borderRadius: 8,
    justifyContent: 'flex-end',
    backgroundColor: Colors.gray_11,
  },
  imageTicket1: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 7,
  },
  imageTicketLine: {
    position: 'absolute',
    left: 250,
    marginTop: 7,
  },
  containerTicketText: {
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  textTicketTitle: {
    ...subhead03,
    color: Colors.gray_12,
    marginBottom: 9,
  },
  textTicketDateActor: {
    ...caption,
    color: Colors.gray_12,
    width: 200,
    marginLeft: 6,
    overflow: 'hidden',
  },
  ticketLine: {
    position: 'absolute',
    top: 10,
    left: 249,
  },
  ticket2: {
    width: 84,
    height: 150,
    backgroundColor: Colors.sub_03,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: -1,
  },
  textReview: {
    ...caption,
    marginTop: 10,
    textAlign: 'center',
    color: Colors.gray_09,
  },
  containerPremiumReviews: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 4,
    alignItems: 'center',
    width: 335,
    height: 44,
    backgroundColor: '#F2F2F2',
    borderRadius: 5,
    paddingHorizontal: 14,
    shadowColor: 'rgba(23, 23, 23, 0)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 5,
  },
  textPremiumReviewTitle: {
    ...subhead02,
    color: Colors.gray_12,
  },
  containerPremiumReviewRanking: {
    width: 24,
    height: 24,
    borderRadius: 4,
    backgroundColor: Colors.primary_01,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  textPremiumReviewRanking: {
    ...subhead02,
    color: Colors.gray_11,
  },
  textPremiumReviewLike: {
    ...caption,
    marginLeft: 4,
    color: Colors.gray_12,
  },
  containerBest: {
    width: 335,
    height: 128,
    borderRadius: 5,
    backgroundColor: '#EDDCFF',
    shadowColor: 'rgba(23, 23, 23, 0.1)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 5,
  },
  textBest: {
    ...subhead03,
    width: '50%',
    marginTop: 20,
    marginLeft: 24,
  },
  containerBestLikeComment: {
    position: 'absolute',
    bottom: 18,
    left: 25,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textBestLikeComment: {
    ...caption,
    color: '#4F4F4F',
    marginHorizontal: 4,
  },
  iconTodayBest: {
    alignSelf: 'flex-end',
    height: undefined,
    aspectRatio: 2,
    resizeMode: 'contain',
  },
  eventBanner: {
    flexDirection: 'row',
    height: 94,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  textEventBannerTitle: {
    ...subhead03,
    color: Colors.gray_12,
  },
  textEventBannerSubTitle: {
    ...bodyLong01,
    color: Colors.gray_08,
  },
  eventBannerPagination: {
    position: 'absolute',
    width: 39,
    height: 18,
    borderRadius: 21,
    bottom: 15,
    right: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textEventBannerPagination: {
    ...caption,
    color: Colors.gray_10,
  },
  imageMusical: {
    width: 125,
    height: 159,
    borderRadius: 9,
    marginBottom: 11,
  },
  textMusicalTitle: {
    ...subhead03,
    color: Colors.gray_12,
    marginBottom: 4,
    overflow: 'hidden',
    width: '100%',
  },
  textMusicalDateLocation: {
    ...caption,
    color: Colors.gray_07,
  },
  containerPoint: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 7.5,
    paddingHorizontal: 15,
    width: 335,
    height: 72,
    borderRadius: 8,
    backgroundColor: Colors.gray_01,
    shadowColor: 'rgba(23, 23, 23, 0.1)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 5,
  },
  textPointTitle: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: -0.6,
    color: Colors.gray_12,
  },
  textPointContent: {
    fontFamily: 'Pretendard-Regular',
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: -0.6,
    color: Colors.gray_08,
  },
  containerPointShortcut: {
    width: 69,
    height: 31,
    borderRadius: 6,
    backgroundColor: Colors.gray_12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textPointShortcut: {
    ...subhead02,
    color: Colors.gray_01,
  },
  resultContainer: {
    flexDirection: 'row',
    marginTop: 21,
    marginHorizontal: 22,
    justifyContent: 'space-between',
  },
  resultText: {
    ...typography.subhead03,
    color: Colors.wireframe_950,
  },
  chip: {
    width: 53,
    height: 24,
    backgroundColor: Colors.sub_05,
    borderRadius: 4.27,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  chipText: {
    color: Colors.gray_01,
    ...typography.subhead01,
  },
  musicalSearchTitle: {
    ...typography.subhead03,
    color: Colors.gray_12,
    marginBottom: 2,
    width: 240,
    overflow: 'hidden',
  },
  seriesSearchText: {
    ...typography.caption,
    color: Colors.gray_08,
  },
  line2: {
    height: 4,
    backgroundColor: Colors.gray_03,
  },
  searchMusicalImage: {
    width: 84,
    height: 92,
    borderRadius: 9,
    marginLeft: 'auto',
  },
});

export default HomeStyles;
